### ISSUE TITLE
Claims not shown on dynmap

### ISSUE THREAD

**Issue by Craze1997** [bloodmc/GDHooks#20]
Hello,

the playerclaims on my server aren't showing up on dynmap.
I use Griefdefender 2.3.2 and GDHooks v0.8-DEV.
![grafik](https://user-images.githubusercontent.com/49312709/215287210-1875a65e-e4b2-44a7-a80a-407f3222e5ac.png)

on Startup GDHooks prints the following message to the console:

> [20:15:43 WARN]: [GDHooks] Plugin GDHooks v0.8-DEV generated an exception while executing task 262
> java.lang.NullPointerException: Cannot invoke "com.griefdefender.api.claim.ClaimManager.getWorldClaims()" because the return value of "com.griefdefender.GDCore.getClaimManager(java.util.UUID)" is null
>         at com.griefdefender.GDCore.getAllClaims(GDCore.java:157) ~[?:?]
>         at com.griefdefender.hooks.provider.DynmapProvider.updateClaims(DynmapProvider.java:261) ~[?:?]
>         at com.griefdefender.hooks.provider.DynmapProvider.access$300(DynmapProvider.java:61) ~[?:?]
>         at com.griefdefender.hooks.provider.DynmapProvider$GriefDefenderUpdate.run(DynmapProvider.java:342) ~[?:?]
>         at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-384]
>         at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-384]
>         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]

How can i fix that?
Thx for help

**Comment by LFLUCA16K** [comment]
HI; I know that's not your problem... could you tell me how to install GDHooks? Thank you

**Comment by Mrs-Feathers** [comment]
what specific build of GDHooks 0.8 do you have? it'll say DEV18 or something. current version is DEV29

**Comment by Mrs-Feathers** [comment]
@LFLUCA16K you download compiled version from the discord server and put it into your plugins folder like normal.
