### ISSUE TITLE
On boot, a class is missing

### ISSUE THREAD

**Issue by Mrs-Feathers** [bloodmc/GDHooks#26]
Hello! I have papermc 1.20.6 installed while i wait for them to release 1.21.. i have griefdefender and GDhooks both latest version so GDHooks dev29. but every time i start my server i get 

`
[15:27:30 INFO]: [GDHooks] Enabling GDHooks v0.8-DEV
[15:27:30 INFO]: [GDHooks] Loading libraries...
[15:27:31 ERROR]: Error occurred while enabling GDHooks v0.8-DEV (Is it up to date?)
java.lang.NoClassDefFoundError: com/griefdefender/hooks/lib/configurate/util/NamingScheme
        at com.griefdefender.hooks.GDHooksBootstrap.onEnable(GDHooksBootstrap.java:147) ~[?:?]
        at gdhooks-bukkit-0.8-DEV29.jar/com.griefdefender.hooks.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:48) ~[gdhooks-bukkit-0.8-DEV29.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.griefdefender.hooks.lib.configurate.util.NamingScheme
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 14 more
`

and the plugin is then disabled with the same error stack. i would like to show stuff on bluemap so i need this plugin but it doesnt seem to be working. what is this issue and how can i fix it?

i downloaded the compiled .jar from discord so i didn't compile it myself

i'm willing to get any information you need, just ask as i don't know what is most useful to help you.

**Comment by Mrs-Feathers** [comment]
'''
[15:27:30 INFO]: [GDHooks] Enabling GDHooks v0.8-DEV
[15:27:30 INFO]: [GDHooks] Loading libraries...
[15:27:31 ERROR]: Error occurred while enabling GDHooks v0.8-DEV (Is it up to date?)
java.lang.NoClassDefFoundError: com/griefdefender/hooks/lib/configurate/util/NamingScheme
        at com.griefdefender.hooks.GDHooksBootstrap.onEnable(GDHooksBootstrap.java:147) ~[?:?]
        at gdhooks-bukkit-0.8-DEV29.jar/com.griefdefender.hooks.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:48) ~[gdhooks-bukkit-0.8-DEV29.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.griefdefender.hooks.lib.configurate.util.NamingScheme
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 14 more
'''
